# ---------------------------------------------------------------------------
# clip.py
# Created on: 2013-01-31 20:32:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
yose_ep_bnd_shp = "C:\\Users\\karlaKing\\Documents\\yosemite\\Yosemite GIS\\Boundary\\yose_ep_bnd.shp"
v2011 = "C:\\Users\\karlaKing\\Documents\\Yosemite\\Landsat TM 5\\09042011\\2011"
Test = "C:\\Users\\karlaKing\\Documents\\landSanFran\\Test"

# Process: Clip
arcpy.Clip_management(v2011, "246268.634282142 4152597.89985766 306576.13986362 4229671.7391046", Test, yose_ep_bnd_shp, "", "ClippingGeometry")

